services:
  - type: web
    name: idea_critique_backend
    env: python
    plan: free
    buildCommand: "cd backend; ./build.sh"
    startCommand: "cd backend; gunicorn idea_critique_backend.wsgi:application"
